from tkinter import *
class Open_S(Frame):
    def __init__(self,master=None):
        Frame.__init__(self,master)
        self.master=master
        self.can=[]
        self.display()
    
    def display(self):
        self.master.geometry("600x400")
        self.can.append(Canvas(self.master,height=250,width=200,bg="white"))
        self.can[0].create_text(100,50,text="Thong tin sinh vien")
        self.can[0].create_text(10,10,text="Id")
        self.can[0].create_text(20,30,text="Name")
        self.can[0].pack()
        self.can[0].place(bordermode=OUTSIDE,x=0,y=0)
        self.frame=Frame(self.master,height=250,width=250)
        self.frame.pack(expand=True,fill=BOTH)
        self.frame.place(x=200,y=0)
        self.can.append(Canvas(self.frame,height=250,width=250,bg="red",scrollregion=(0,0,500,500)))
        self.Xbar=Scrollbar(self.frame,command=self.can[1].xview,orient=HORIZONTAL)
        self.Xbar.pack(side=BOTTOM,fill=X)
        self.Ybar=Scrollbar(self.frame,command=self.can[1].yview)
        self.Ybar.pack(side=RIGHT,fill=Y)
        self.can[1].create_text(300,300,text="Hello",fill="Blue")
        self.can[1].config(xscrollcommand=self.Xbar.set,yscrollcommand=self.Ybar.set)
        self.can[1].pack(expand=True,fill=BOTH)
        A=Button(self.master,text = "Join class",width=17,height=5,bg="yellow")
        A.pack()
        A.place(x=470,y=0)
        B=Button(self.master,text = "Resign class",width=17,height=5,bg="blue")
        B.pack()
        B.place(x=470,y=80)
        C=Button(self.master,text = "Change info",bg="red")
        C.pack()
        C.place(x=70,y=250)
        D=Button(self.master,text = "backPage",bg="orange")
        D.pack()
        D.place(x=200,y=270)
        E=Button(self.master,text = "nextPge",bg="orange")
        E.pack()
        E.place(x=400,y=270)
        self.master.mainloop()
App=Open_S(Tk())